version: '3.9'

services:

  langroid_database:
    build:
      context: ./docker/
      dockerfile: postgres.Dockerfile
    restart: always
    environment:
      POSTGRES_DB: domtik_database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    container_name: langroid_database
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/bitnami/postgresql/
      - ./docker/init_database.sql:/docker-entrypoint-initdb.d/init_database.sql


  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "root@root.root"
      PGADMIN_DEFAULT_PASSWORD: "root"
    container_name: langroid_pgadmin
    ports:
      - "5052:80"
    volumes:
      - postgres_data:/var/lib/pgadmin

  rabbitmq:
    image: rabbitmq
    command: rabbitmq-server
    expose:
      - 5672
      - 15672
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 5s
      timeout: 15s
      retries: 1


volumes:
  postgres_data:




